import React from 'react';
import { motion } from 'framer-motion';
import { ActivitySquare, BrainCircuit, LineChart, MessageSquareWarning, Network, Cpu } from 'lucide-react';

const featuresList = [
  {
    icon: Network,
    title: "Real-Time Data Ingestion",
    description: "Stream millions of posts seamlessly from Twitter, Reddit, and global news APIS into our processing engine."
  },
  {
    icon: BrainCircuit,
    title: "Sentiment Analysis Engine",
    description: "Advanced NLP pipelines to instantly classify emotional tone, sarcasm, and nuanced language patterns."
  },
  {
    icon: ActivitySquare,
    title: "Anomaly Detection",
    description: "Multi-dimensional algorithms to pinpoint unexpected spikes in negative volume before they trend.",
    highlight: true
  },
  {
    icon: LineChart,
    title: "Sliding Window Trend Analysis",
    description: "Continuous evaluation of rolling time windows to establish baseline norms and detect deviations."
  },
  {
    icon: Cpu,
    title: "RAG-based AI Recommendations",
    description: "Context-aware response suggestions generated by integrating incident data with custom playbook knowledge."
  },
  {
    icon: MessageSquareWarning,
    title: "Multi-Platform Monitoring",
    description: "Unified dashboard bridging disparate social channels to track cross-platform crisis propagation."
  }
];

const Features = () => {
  return (
    <section id="features" className="py-24 relative px-6">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-sm font-semibold text-accent-neon tracking-widest uppercase mb-3">Core System</h2>
          <h3 className="text-3xl md:text-5xl font-bold mb-6">Engineered for <span className="text-gradient">Intelligence</span></h3>
          <p className="text-gray-400 max-w-2xl mx-auto text-lg">
            Our proprietary modular architecture combines high-throughput streaming with advanced machine learning paradigms.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {featuresList.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1, duration: 0.5 }}
              className={`glass-card p-8 rounded-2xl glass-card-hover group relative ${feature.highlight ? 'border-primary/50 shadow-[0_0_30px_rgba(155,48,255,0.15)] bg-primary/5' : ''}`}
            >
              {feature.highlight && (
                <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-accent-violet/10 rounded-2xl pointer-events-none" />
              )}
              <div className="mb-6 inline-flex p-4 rounded-xl bg-dark-800 border border-white/5 group-hover:border-primary/30 transition-colors relative">
                <feature.icon className={`w-8 h-8 ${feature.highlight ? 'text-primary-light' : 'text-accent-neon'}`} />
                {feature.highlight && (
                  <div className="absolute inset-0 bg-primary/20 blur-xl rounded-xl opacity-0 group-hover:opacity-100 transition-opacity" />
                )}
              </div>
              <h4 className="text-xl font-bold text-white mb-3">{feature.title}</h4>
              <p className="text-gray-400 leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
